# Uncomment this line to define a global platform for your project
source 'git@gitlab.alibaba-inc.com:alipods/specs-mirror.git'

platform :ios, "7.0"

def demo_pods
    pod 'MJRefresh'
    pod 'SDWebImage'
end

def sdk_pods
end

target 'Demo' do
    platform :ios, '7.0'
    demo_pods
#    pod 'JUFLXLayoutKit', :path => '~/Ali/JUFLXLayoutKit/JUFLXLayoutKit.podspec'
#    pod 'JUFLXLayoutDebugger', :path => '~/Ali/JUFLXLayoutDebugger/JUFLXLayoutDebugger.podspec', :configurations => ['Debug']
end

target 'LuaViewSDK' do
    platform :ios, '7.0'
    sdk_pods
end

